// Generated by gencpp from file gripper_pkg/servoService.msg
// DO NOT EDIT!


#ifndef GRIPPER_PKG_MESSAGE_SERVOSERVICE_H
#define GRIPPER_PKG_MESSAGE_SERVOSERVICE_H

#include <ros/service_traits.h>


#include <gripper_pkg/servoServiceRequest.h>
#include <gripper_pkg/servoServiceResponse.h>


namespace gripper_pkg
{

struct servoService
{

typedef servoServiceRequest Request;
typedef servoServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct servoService
} // namespace gripper_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gripper_pkg::servoService > {
  static const char* value()
  {
    return "397e5d9373b2d6be3b1e90928218304b";
  }

  static const char* value(const ::gripper_pkg::servoService&) { return value(); }
};

template<>
struct DataType< ::gripper_pkg::servoService > {
  static const char* value()
  {
    return "gripper_pkg/servoService";
  }

  static const char* value(const ::gripper_pkg::servoService&) { return value(); }
};


// service_traits::MD5Sum< ::gripper_pkg::servoServiceRequest> should match 
// service_traits::MD5Sum< ::gripper_pkg::servoService > 
template<>
struct MD5Sum< ::gripper_pkg::servoServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gripper_pkg::servoService >::value();
  }
  static const char* value(const ::gripper_pkg::servoServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gripper_pkg::servoServiceRequest> should match 
// service_traits::DataType< ::gripper_pkg::servoService > 
template<>
struct DataType< ::gripper_pkg::servoServiceRequest>
{
  static const char* value()
  {
    return DataType< ::gripper_pkg::servoService >::value();
  }
  static const char* value(const ::gripper_pkg::servoServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gripper_pkg::servoServiceResponse> should match 
// service_traits::MD5Sum< ::gripper_pkg::servoService > 
template<>
struct MD5Sum< ::gripper_pkg::servoServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gripper_pkg::servoService >::value();
  }
  static const char* value(const ::gripper_pkg::servoServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gripper_pkg::servoServiceResponse> should match 
// service_traits::DataType< ::gripper_pkg::servoService > 
template<>
struct DataType< ::gripper_pkg::servoServiceResponse>
{
  static const char* value()
  {
    return DataType< ::gripper_pkg::servoService >::value();
  }
  static const char* value(const ::gripper_pkg::servoServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRIPPER_PKG_MESSAGE_SERVOSERVICE_H
