// Generated by gencpp from file gripper_pkg/stepServiceRequest.msg
// DO NOT EDIT!


#ifndef GRIPPER_PKG_MESSAGE_STEPSERVICEREQUEST_H
#define GRIPPER_PKG_MESSAGE_STEPSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gripper_pkg
{
template <class ContainerAllocator>
struct stepServiceRequest_
{
  typedef stepServiceRequest_<ContainerAllocator> Type;

  stepServiceRequest_()
    : distance(0.0)
    , initialise(false)
    , direction(false)  {
    }
  stepServiceRequest_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , initialise(false)
    , direction(false)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;

   typedef uint8_t _initialise_type;
  _initialise_type initialise;

   typedef uint8_t _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct stepServiceRequest_

typedef ::gripper_pkg::stepServiceRequest_<std::allocator<void> > stepServiceRequest;

typedef boost::shared_ptr< ::gripper_pkg::stepServiceRequest > stepServiceRequestPtr;
typedef boost::shared_ptr< ::gripper_pkg::stepServiceRequest const> stepServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_pkg::stepServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gripper_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'gripper_pkg': ['/home/husarion/ros_ws/devel/share/gripper_pkg/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f3b907e7729c265b422f7699d410011";
  }

  static const char* value(const ::gripper_pkg::stepServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f3b907e7729c265ULL;
  static const uint64_t static_value2 = 0xb422f7699d410011ULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_pkg/stepServiceRequest";
  }

  static const char* value(const ::gripper_pkg::stepServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n\
bool initialise\n\
bool direction\n\
";
  }

  static const char* value(const ::gripper_pkg::stepServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.initialise);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stepServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_pkg::stepServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gripper_pkg::stepServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "initialise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.initialise);
    s << indent << "direction: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_PKG_MESSAGE_STEPSERVICEREQUEST_H
