// Generated by gencpp from file gripper_pkg/stepActionGoal.msg
// DO NOT EDIT!


#ifndef GRIPPER_PKG_MESSAGE_STEPACTIONGOAL_H
#define GRIPPER_PKG_MESSAGE_STEPACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gripper_pkg
{
template <class ContainerAllocator>
struct stepActionGoal_
{
  typedef stepActionGoal_<ContainerAllocator> Type;

  stepActionGoal_()
    : distance(0.0)  {
    }
  stepActionGoal_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::gripper_pkg::stepActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_pkg::stepActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct stepActionGoal_

typedef ::gripper_pkg::stepActionGoal_<std::allocator<void> > stepActionGoal;

typedef boost::shared_ptr< ::gripper_pkg::stepActionGoal > stepActionGoalPtr;
typedef boost::shared_ptr< ::gripper_pkg::stepActionGoal const> stepActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_pkg::stepActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_pkg::stepActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gripper_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'gripper_pkg': ['/home/husarion/ros_ws/devel/share/gripper_pkg/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gripper_pkg::stepActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_pkg::stepActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_pkg::stepActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_pkg::stepActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_pkg::stepActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_pkg::stepActionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_pkg::stepActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::gripper_pkg::stepActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_pkg::stepActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_pkg/stepActionGoal";
  }

  static const char* value(const ::gripper_pkg::stepActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_pkg::stepActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
float32 distance # distance to move the stepper\n\
";
  }

  static const char* value(const ::gripper_pkg::stepActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_pkg::stepActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stepActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_pkg::stepActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gripper_pkg::stepActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_PKG_MESSAGE_STEPACTIONGOAL_H
