// Generated by gencpp from file gripper_pkg/stepActionActionGoal.msg
// DO NOT EDIT!


#ifndef GRIPPER_PKG_MESSAGE_STEPACTIONACTIONGOAL_H
#define GRIPPER_PKG_MESSAGE_STEPACTIONACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <gripper_pkg/stepActionGoal.h>

namespace gripper_pkg
{
template <class ContainerAllocator>
struct stepActionActionGoal_
{
  typedef stepActionActionGoal_<ContainerAllocator> Type;

  stepActionActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  stepActionActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::gripper_pkg::stepActionGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct stepActionActionGoal_

typedef ::gripper_pkg::stepActionActionGoal_<std::allocator<void> > stepActionActionGoal;

typedef boost::shared_ptr< ::gripper_pkg::stepActionActionGoal > stepActionActionGoalPtr;
typedef boost::shared_ptr< ::gripper_pkg::stepActionActionGoal const> stepActionActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gripper_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'gripper_pkg': ['/home/husarion/ros_ws/devel/share/gripper_pkg/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2079ead51a69a425b7a9cc0526d0f53b";
  }

  static const char* value(const ::gripper_pkg::stepActionActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2079ead51a69a425ULL;
  static const uint64_t static_value2 = 0xb7a9cc0526d0f53bULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_pkg/stepActionActionGoal";
  }

  static const char* value(const ::gripper_pkg::stepActionActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
stepActionGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: gripper_pkg/stepActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
float32 distance # distance to move the stepper\n\
bool direction\n\
bool initialise \n\
";
  }

  static const char* value(const ::gripper_pkg::stepActionActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stepActionActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_pkg::stepActionActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gripper_pkg::stepActionActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::gripper_pkg::stepActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_PKG_MESSAGE_STEPACTIONACTIONGOAL_H
