; Auto-generated. Do not edit!


(cl:in-package gripper_pkg-msg)


;//! \htmlinclude stepActionFeedback.msg.html

(cl:defclass <stepActionFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_complete
    :reader percent_complete
    :initarg :percent_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass stepActionFeedback (<stepActionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <stepActionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'stepActionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gripper_pkg-msg:<stepActionFeedback> is deprecated: use gripper_pkg-msg:stepActionFeedback instead.")))

(cl:ensure-generic-function 'percent_complete-val :lambda-list '(m))
(cl:defmethod percent_complete-val ((m <stepActionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gripper_pkg-msg:percent_complete-val is deprecated.  Use gripper_pkg-msg:percent_complete instead.")
  (percent_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <stepActionFeedback>) ostream)
  "Serializes a message object of type '<stepActionFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <stepActionFeedback>) istream)
  "Deserializes a message object of type '<stepActionFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<stepActionFeedback>)))
  "Returns string type for a message object of type '<stepActionFeedback>"
  "gripper_pkg/stepActionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'stepActionFeedback)))
  "Returns string type for a message object of type 'stepActionFeedback"
  "gripper_pkg/stepActionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<stepActionFeedback>)))
  "Returns md5sum for a message object of type '<stepActionFeedback>"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'stepActionFeedback)))
  "Returns md5sum for a message object of type 'stepActionFeedback"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<stepActionFeedback>)))
  "Returns full string definition for message of type '<stepActionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message ~%float32 percent_complete # ~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'stepActionFeedback)))
  "Returns full string definition for message of type 'stepActionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message ~%float32 percent_complete # ~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <stepActionFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <stepActionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'stepActionFeedback
    (cl:cons ':percent_complete (percent_complete msg))
))
