; Auto-generated. Do not edit!


(cl:in-package gripper_pkg-msg)


;//! \htmlinclude stepActionGoal.msg.html

(cl:defclass <stepActionGoal> (roslisp-msg-protocol:ros-message)
  ((distance
    :reader distance
    :initarg :distance
    :type cl:float
    :initform 0.0)
   (direction
    :reader direction
    :initarg :direction
    :type cl:boolean
    :initform cl:nil)
   (initialise
    :reader initialise
    :initarg :initialise
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass stepActionGoal (<stepActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <stepActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'stepActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gripper_pkg-msg:<stepActionGoal> is deprecated: use gripper_pkg-msg:stepActionGoal instead.")))

(cl:ensure-generic-function 'distance-val :lambda-list '(m))
(cl:defmethod distance-val ((m <stepActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gripper_pkg-msg:distance-val is deprecated.  Use gripper_pkg-msg:distance instead.")
  (distance m))

(cl:ensure-generic-function 'direction-val :lambda-list '(m))
(cl:defmethod direction-val ((m <stepActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gripper_pkg-msg:direction-val is deprecated.  Use gripper_pkg-msg:direction instead.")
  (direction m))

(cl:ensure-generic-function 'initialise-val :lambda-list '(m))
(cl:defmethod initialise-val ((m <stepActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gripper_pkg-msg:initialise-val is deprecated.  Use gripper_pkg-msg:initialise instead.")
  (initialise m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <stepActionGoal>) ostream)
  "Serializes a message object of type '<stepActionGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'distance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'direction) 1 0)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'initialise) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <stepActionGoal>) istream)
  "Deserializes a message object of type '<stepActionGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'distance) (roslisp-utils:decode-single-float-bits bits)))
    (cl:setf (cl:slot-value msg 'direction) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:setf (cl:slot-value msg 'initialise) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<stepActionGoal>)))
  "Returns string type for a message object of type '<stepActionGoal>"
  "gripper_pkg/stepActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'stepActionGoal)))
  "Returns string type for a message object of type 'stepActionGoal"
  "gripper_pkg/stepActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<stepActionGoal>)))
  "Returns md5sum for a message object of type '<stepActionGoal>"
  "310977177aeb6144200c4906d67a11ee")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'stepActionGoal)))
  "Returns md5sum for a message object of type 'stepActionGoal"
  "310977177aeb6144200c4906d67a11ee")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<stepActionGoal>)))
  "Returns full string definition for message of type '<stepActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32 distance # distance to move the stepper~%bool direction~%bool initialise ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'stepActionGoal)))
  "Returns full string definition for message of type 'stepActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float32 distance # distance to move the stepper~%bool direction~%bool initialise ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <stepActionGoal>))
  (cl:+ 0
     4
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <stepActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'stepActionGoal
    (cl:cons ':distance (distance msg))
    (cl:cons ':direction (direction msg))
    (cl:cons ':initialise (initialise msg))
))
