local_costmap:
  update_frequency: 5
  publish_frequency: 5
  static_map: false
  rolling_window: true
  width: 2
  height: 2
  resolution: 0.05

  inflater_layer:
    inflation_radius: 0.25
    cost_scaling_factor: 0.5


  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, clearing: true, marking: true}
    obstacle_range: 10
    raytrace_range: 11

  plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}