; Auto-generated. Do not edit!


(cl:in-package gripper_pkg-msg)


;//! \htmlinclude stepActionResult.msg.html

(cl:defclass <stepActionResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass stepActionResult (<stepActionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <stepActionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'stepActionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gripper_pkg-msg:<stepActionResult> is deprecated: use gripper_pkg-msg:stepActionResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <stepActionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gripper_pkg-msg:success-val is deprecated.  Use gripper_pkg-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <stepActionResult>) ostream)
  "Serializes a message object of type '<stepActionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <stepActionResult>) istream)
  "Deserializes a message object of type '<stepActionResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<stepActionResult>)))
  "Returns string type for a message object of type '<stepActionResult>"
  "gripper_pkg/stepActionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'stepActionResult)))
  "Returns string type for a message object of type 'stepActionResult"
  "gripper_pkg/stepActionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<stepActionResult>)))
  "Returns md5sum for a message object of type '<stepActionResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'stepActionResult)))
  "Returns md5sum for a message object of type 'stepActionResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<stepActionResult>)))
  "Returns full string definition for message of type '<stepActionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the results~%bool success # was the action successful?~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'stepActionResult)))
  "Returns full string definition for message of type 'stepActionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the results~%bool success # was the action successful?~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <stepActionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <stepActionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'stepActionResult
    (cl:cons ':success (success msg))
))
